### ISSUE TITLE
Can't understand how to get it running on Windows10 64 bit

### ISSUE THREAD

**Issue by IvankoB** [virtualsquare/vde-2#28]
We use this software intensively and lack it on Windows

**Comment by danielinux** [comment]
Hello!
Windows is not supported. None of the developers is windows user, so we never spent any time on it. 

Vde2 requires a POSIX-compilant OS, and a tun/tap driver. It might be possible to port it to windows, but we don't have plans to do it, at the moment.

However, we would welcome contributions for ports on operating systems that are not yet supported.

**Comment by hgkamath** [comment]
Windows-TAP drver can be installed as a independent entity and a TAP interface  can be created if required.    
https://github.com/OpenVPN/tap-windows6

For the OS-features that this software uses, the posix compatibility layers that mingw compiler provides might be sufficient.    
One should try compiling with mingw and see what issues one runs into.  

but yes, getting a windows port going with pre-built-exe in github-releases should be an valid tracking Bug.  
Windows users needs it more than Linux, because its so hard to do bridging/virtual switch in windows for qemu-VMs.    
https://gitlab.com/qemu-project/qemu/-/issues/2364
