### ISSUE TITLE
Consider adding mbedtls as alternative crypto implementation

### ISSUE THREAD

**Issue by evelikov** [virtualsquare/vde-2#50]
Greetings team,

I was going through some maintenance on my Arch machines and noticed that vde2 depends on wolfssl the only [package to do so in Arch](https://archlinux.org/packages/extra/x86_64/wolfssl/). Looking through Debian 12 (stable) - via `apt-cache rdepends libwolfssl35` shows two instances:
 - libvdeplug-agno - vde plugin
 - lighttpd-mod-wolfssl - libghttpd module

AFAICT the vde2 code, replies only on crypto/chacha20. For which there are alternatives - openssl, mbedtls and libgcrypt.

Seems like vde2 used to do openssl yet was removed a few years ago https://github.com/virtualsquare/vde-2/commit/8599321526d0a31925fe55cabbe132b752cb268a. On the other hand, I don't have the best of experience with libgcrypt - we had MT issues [when we tried it in mesa](https://gitlab.freedesktop.org/mesa/mesa/-/commit/ade3108bb5b074013417b31e61b8077ccefb7484).

This sort of leaves us with mbedtls. Would the project be OK with adding it as an alternative, or replacement perhaps?

Mind you, I don't think I'd have the time to write patches anytime soon.

Thanks o/

**Comment by danielinux** [comment]
What would be the advantage of adding mbedTLS support?
Arch needs a better wolfSSL packaging strategy, perhaps it's worth fixing that.

mbedTLS can't really be compared to wolfSSL in terms of features, vulnerability management and support.  It is just a toy/demo project, and it's not worth porting that chacha module to yet another library.

If you think it's a feature worth your time, we might consider a PR, but if it's a mere feature request I don't see how this can be accomplished.

**Comment by danielinux** [comment]
Maybe Arch has not enough package support for daemons and tools for multiple TLS/crypto.

Many projects include wolfSSL support, either natively in their codebase or via [the wolfssl's OSP repository, that's maintained by wolfSSL developers.](https://github.com/wolfssl/osp). OpenSSL applications can be linked with wolfSSL via compatibility layer.

My opinion on this:
While I think OpenSSL is "too much" and limits the portability to embedded Linux, besides being unstable lately with a massive change of APIs switching from v1 to v3; on the other hand, mbedTLS is "not enough" (used, maintained, supported) to be even relevant in such a comparison.

Even if I agree this use case is simple enough for a fit, I would rather not support that project.

**Comment by danielinux** [comment]
> didn't realise the maintainer of this project is working on wolfssl

I have contributed to vde-2 but I'm not the main author or the maintainer. It just happens that the component that needs chacha (vde_cryptcab) has been originally authored by me. OpenSSL used to require a license exception, so we switched to wolfSSL.

Package management superficiality is not really upsetting, not looking at modern distros for PCs. wolfSSL is much more popular in embedded/baremetal/RTOS, it has been the default on OpenWRT for a long time, and gnu distros is really not a way to measure its popularity. I could not be bothered less.

> Sorry, I don't follow - can you elaborate?

I will not write a patch to include support for mbedTLS in vde.  It is a regression.

If someone else wants to, I'm happy to review and merge. I agree choice  is important. I would not like for it to be a replacement, but rather an alternative, since I consider that a quality regression.

I don't think this is a good choice in general because of the state of the mbedTLS project and the potential vulnerabilities emerging in the codebase that are (historically) not prioritized in the right way, and may affect users who rely on cryptcab for making simple VPNs across virtual switches. mbedTLS team is undersized for the kind of projects they aspire to be maintaining, and takes forever to include new features or react to reports.

I believe that there are alternatives for you, e.g. compiling vde without cryptcab for your Arch package, which would remove the dependency from wolfSSL. 

> Mind you, I don't think I'd have the time to write patches anytime soon.

Unless someone steps up to actually do the porting, I would close this as "wontfix". Feel free to re-open/reference once you have a patch.

**Comment by danielinux** [comment]
I never said I was in a hurry to close this. I said "unless someone steps up", which actually happened faster than I expected. Thanks a lot for the contribution.

**Comment by danielinux** [comment]
> Apologies if I struck a nerve there

@evelikov  I understand why you sense that bringing my personal opinion to this conversation might have been driven by a mere conflict of interest, but there is more than that. I am convinced about the difference in quality a properly maintained crypto implementation with a structured process can make. 

I'm sure you are familiar with the fact that popularity for libraries in desktop distributions is biased towards permissive licenses allowing for a common platform also for proprietary/closed source software to use pillar APIs that nowaday are considered a commodity, including in fact TLS and cryptography.  In order to accommodate non-free software, distribution maintainers must take decisions that imply trade-offs. In my opinion, when this is done without providing alternatives, also for headless systems where not as much flexibility is required, there is a blind unbalance penalizing security aspects.

Some less popular distributions are already working towards replacing openSSL, and it might make sense for those use cases where the security management is critical.

**Comment by evelikov** [comment]
This has been resolved with https://github.com/virtualsquare/vde-2/pull/56

Thanks for the help everyone.
